language: C
os: linux
dist: xenial
script:
- mkdir -p build
- cd build
- cmake ..
- make
- make test
after_success:
- cd ..
- cd script
- chmod +x auto_merge.sh
- "./auto_merge.sh"
env:
  global:
  - secure: 79AinkuAwlh4RiDvnaFu2bPIZ1ATVW00aDVa/IVcjrNfMgXblPVP8ZW3OiMSj31j1xW0JKP1zQxuTE2PuF6yiljFB67K1xS2w9ag3M0VqCthSAJR2CgN1dyXE1iJYSCwj0GOa5nG4yKlDlqaFftdcw4r77GJA8zAjnuod5L0f+vKB/pjao4GgGjn9n+GEUnGVaAvZiBuhXhEYsEfa5aTuLN03UfiwTvp1Udwrgwkgbxfr+wlilaLntvMiNvGY/nKhfeHdHL+dDDst00rEhs+UPqWipcPCvvkrZ58x1RpYEnHTk3x8MvU+11qMCyIwgCpIoLbYNxMMwSCrB66b94YjEUDthwA3//+JHRyZyjuB+tJkctxddhsGAO7OCcgJOyw07mtP6KA9cHo0GvP2OtLhnmpg/xaItZ728jFpGjEUhVonAbw33RKQmmP0qi+Eco/LoCozVRcL/MEGYAUeyA9s+/P3YLr27ZoYPxzAL1SUYvVUatBxWAuKBaTsFyCrvfRNed8JVjGs3w7VP1qvsLh9B+hfDs6DyuYRbmNhNdnW3ld7UVvAjKAoRU0kUHyJKNGkqXgHefkF2+Y1AVb0ngj3i6GwLYVRK7Zjx/+vZmUnJivahnS3gtVfhEf0PM5YPS29+YUJJITsM/+47BJPmXSUQ5azODu2Uq+13pY/ZeoICw=
